# Generated by Django 5.0.1 on 2024-04-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.FileField(default='', upload_to='Vehicles/'),
        ),
    ]
