# Generated by Django 5.0.1 on 2024-04-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca_app', '0002_remove_user_city_remove_user_vehicle_booking_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
