# Generated by Django 5.0.1 on 2024-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca_app', '0003_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.CharField(default='★★★★★', max_length=10),
        ),
    ]
