# Generated by Django 5.0.3 on 2024-05-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca_app', '0005_rename_raitng_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(default='Admin', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='vehicle',
            new_name='vehicle_img',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment',
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
