# Generated by Django 5.0.3 on 2024-05-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sca_app', '0006_admin_rename_vehicle_booking_vehicle_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminMod',
        ),
    ]
