# Generated by Django 5.0.3 on 2024-05-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca_app', '0008_adminmod_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.TextField(default='BBD University, Lucknow'),
        ),
    ]
