# Generated by Django 5.0.3 on 2024-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca_app', '0011_alter_company_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='idcard',
            field=models.FileField(default='', upload_to='IDCARDS/'),
        ),
    ]
