# Generated by Django 5.0.3 on 2024-05-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sca_app', '0012_company_idcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
