# Generated by Django 5.0.3 on 2024-05-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sca_app', '0013_company_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
    ]
